# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_tabWidget_container.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tabWidgetContainer(object):
    def setupUi(self, tabWidgetContainer):
        tabWidgetContainer.setObjectName("tabWidgetContainer")
        tabWidgetContainer.resize(1091, 817)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(tabWidgetContainer)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget_content = QtWidgets.QTabWidget(tabWidgetContainer)
        self.tabWidget_content.setMinimumSize(QtCore.QSize(200, 300))
        self.tabWidget_content.setObjectName("tabWidget_content")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(1)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_keyType = QtWidgets.QLabel(self.layoutWidget)
        self.label_keyType.setObjectName("label_keyType")
        self.horizontalLayout.addWidget(self.label_keyType)
        self.lineEdit_keyTitle = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_keyTitle.setObjectName("lineEdit_keyTitle")
        self.horizontalLayout.addWidget(self.lineEdit_keyTitle)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(20, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_field_count = QtWidgets.QLabel(self.layoutWidget)
        self.label_field_count.setObjectName("label_field_count")
        self.horizontalLayout.addWidget(self.label_field_count)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(20, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.pushButton_rebanehas = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_rebanehas.setObjectName("pushButton_rebanehas")
        self.horizontalLayout.addWidget(self.pushButton_rebanehas)
        self.pushButton_deletehas = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_deletehas.setObjectName("pushButton_deletehas")
        self.horizontalLayout.addWidget(self.pushButton_deletehas)
        self.pushButton_setTTL = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_setTTL.setObjectName("pushButton_setTTL")
        self.horizontalLayout.addWidget(self.pushButton_setTTL)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tableWidget_values = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget_values.setMinimumSize(QtCore.QSize(0, 100))
        self.tableWidget_values.setObjectName("tableWidget_values")
        self.tableWidget_values.setColumnCount(0)
        self.tableWidget_values.setRowCount(0)
        self.horizontalLayout_6.addWidget(self.tableWidget_values)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_addRow = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_addRow.sizePolicy().hasHeightForWidth())
        self.pushButton_addRow.setSizePolicy(sizePolicy)
        self.pushButton_addRow.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_addRow.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_addRow.setObjectName("pushButton_addRow")
        self.verticalLayout.addWidget(self.pushButton_addRow)
        self.pushButton_deleteRow = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_deleteRow.sizePolicy().hasHeightForWidth())
        self.pushButton_deleteRow.setSizePolicy(sizePolicy)
        self.pushButton_deleteRow.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_deleteRow.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_deleteRow.setObjectName("pushButton_deleteRow")
        self.verticalLayout.addWidget(self.pushButton_deleteRow)
        self.pushButton_reloadRow = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_reloadRow.sizePolicy().hasHeightForWidth())
        self.pushButton_reloadRow.setSizePolicy(sizePolicy)
        self.pushButton_reloadRow.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_reloadRow.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_reloadRow.setObjectName("pushButton_reloadRow")
        self.verticalLayout.addWidget(self.pushButton_reloadRow)
        self.lineEdit_search = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_search.sizePolicy().hasHeightForWidth())
        self.lineEdit_search.setSizePolicy(sizePolicy)
        self.lineEdit_search.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_search.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.verticalLayout.addWidget(self.lineEdit_search)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(48, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setMaximumSize(QtCore.QSize(48, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_feildsize = QtWidgets.QLabel(self.layoutWidget1)
        self.label_feildsize.setMinimumSize(QtCore.QSize(20, 0))
        self.label_feildsize.setObjectName("label_feildsize")
        self.horizontalLayout_3.addWidget(self.label_feildsize)
        self.label_field_size = QtWidgets.QLabel(self.layoutWidget1)
        self.label_field_size.setObjectName("label_field_size")
        self.horizontalLayout_3.addWidget(self.label_field_size)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(20, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBox_keyViewas = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_keyViewas.setObjectName("comboBox_keyViewas")
        self.comboBox_keyViewas.addItem("")
        self.comboBox_keyViewas.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_keyViewas)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.textEdit_key = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_key.setMinimumSize(QtCore.QSize(0, 50))
        self.textEdit_key.setMaximumSize(QtCore.QSize(16777215, 80))
        self.textEdit_key.setObjectName("textEdit_key")
        self.verticalLayout_2.addWidget(self.textEdit_key)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_valuesize = QtWidgets.QLabel(self.layoutWidget1)
        self.label_valuesize.setMinimumSize(QtCore.QSize(20, 0))
        self.label_valuesize.setObjectName("label_valuesize")
        self.horizontalLayout_4.addWidget(self.label_valuesize)
        self.label_valus_size = QtWidgets.QLabel(self.layoutWidget1)
        self.label_valus_size.setObjectName("label_valus_size")
        self.horizontalLayout_4.addWidget(self.label_valus_size)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setMinimumSize(QtCore.QSize(20, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.comboBox_valueViewas = QtWidgets.QComboBox(self.layoutWidget1)
        self.comboBox_valueViewas.setObjectName("comboBox_valueViewas")
        self.comboBox_valueViewas.addItem("")
        self.comboBox_valueViewas.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_valueViewas)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.textEdit_value = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_value.setMinimumSize(QtCore.QSize(0, 50))
        self.textEdit_value.setObjectName("textEdit_value")
        self.verticalLayout_2.addWidget(self.textEdit_value)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.pushButton_save = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_5.addWidget(self.pushButton_save)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addWidget(self.splitter)
        self.tabWidget_content.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_2.setLineWidth(0)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(1)
        self.splitter_2.setObjectName("splitter_2")
        self.listWidget = QtWidgets.QListWidget(self.splitter_2)
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(self.splitter_2)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_6.addWidget(self.splitter_2)
        self.tabWidget_content.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.tabWidget_content)

        self.retranslateUi(tabWidgetContainer)
        self.tabWidget_content.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(tabWidgetContainer)

    def retranslateUi(self, tabWidgetContainer):
        _translate = QtCore.QCoreApplication.translate
        tabWidgetContainer.setWindowTitle(_translate("tabWidgetContainer", "Form"))
        self.label_keyType.setText(_translate("tabWidgetContainer", "HASH:"))
        self.label_2.setText(_translate("tabWidgetContainer", "size:  "))
        self.label_field_count.setText(_translate("tabWidgetContainer", " "))
        self.label_3.setText(_translate("tabWidgetContainer", "TTL:  "))
        self.pushButton_rebanehas.setText(_translate("tabWidgetContainer", "Rename"))
        self.pushButton_deletehas.setText(_translate("tabWidgetContainer", "Delete"))
        self.pushButton_setTTL.setText(_translate("tabWidgetContainer", "Set TTL"))
        self.pushButton_addRow.setText(_translate("tabWidgetContainer", "Add row"))
        self.pushButton_deleteRow.setText(_translate("tabWidgetContainer", "Delete row"))
        self.pushButton_reloadRow.setText(_translate("tabWidgetContainer", "Reload row"))
        self.pushButton_2.setText(_translate("tabWidgetContainer", "<"))
        self.pushButton.setText(_translate("tabWidgetContainer", ">"))
        self.label_feildsize.setText(_translate("tabWidgetContainer", "size:  "))
        self.label_field_size.setText(_translate("tabWidgetContainer", " "))
        self.label_5.setText(_translate("tabWidgetContainer", "View as:"))
        self.comboBox_keyViewas.setItemText(0, _translate("tabWidgetContainer", "Plain Text"))
        self.comboBox_keyViewas.setItemText(1, _translate("tabWidgetContainer", "Json"))
        self.textEdit_key.setHtml(_translate("tabWidgetContainer", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_valuesize.setText(_translate("tabWidgetContainer", "size:  "))
        self.label_valus_size.setText(_translate("tabWidgetContainer", " "))
        self.label_6.setText(_translate("tabWidgetContainer", "View as:"))
        self.comboBox_valueViewas.setItemText(0, _translate("tabWidgetContainer", "Plain Text"))
        self.comboBox_valueViewas.setItemText(1, _translate("tabWidgetContainer", "Json"))
        self.pushButton_save.setText(_translate("tabWidgetContainer", "save"))
        self.tabWidget_content.setTabText(self.tabWidget_content.indexOf(self.tab), _translate("tabWidgetContainer", "Tab 1"))
        self.tabWidget_content.setTabText(self.tabWidget_content.indexOf(self.tab_2), _translate("tabWidgetContainer", "页"))
